branches:
  only:
  - master
language: python
python:
- 2.7
install:
- pip install -r requirements.txt --use-mirrors
script:
- make html
notifications:
  email: false
env:
  global:
  - secure: b3hKKSjpVP95+bUVZ0DrGIYC/z4HlEq8aNsEV2y4jzuP5k1pE0nzEgJaJ9Ym+W6p1VBJwYYEUbLwAccILaDIvimqWkmqvkyqq15DXcPwPU0evLoouucUuT5IJKczU7zNzi42pWS/Bg7UqoYQZj6QD+jbOf4GAMVdcpqdVw9bVAbUf3R24FbRVHyRZaKO7ytbgcSR9sGHxvYo00Po9aTXRPJkGV6uvXiGvn/gvvUgM+xD3sPD4reWwnLRb+H0m35euWtSOrWIiUxptj4L8nOZqV3gPlYvgJ5Mr0W28iVs+7ft47vARLxJlaUYt+VscCKtEmnpXtgEjrQPpSILvv5X8WW8l9/lEEwiywebfAoEqmIbhNSwSt1anayVpQxyQQBac3ZhxfJ/umDBacDyHHx6tadq1Q1C84Rd0j3huINk+rBcNVwQKhbDxeeelvgtdYYVzw4ic0wF3VJwZvkVqy/ffeGnxrlhNPZMg+7t4PVPubqOSC6RbF+JOWt3HWLyyT+s83SxzTt1iDi79xikL/hPWkJP2q4iWtF8Au9Hs1usHzv1Aqz7lk5kq9eHqGTrDi725Fo3CiTIYbhQuUKTcsppRhHvgiY8Ft6t9Uz/Dyp6ptqZBtV5hmKFeG4cvSJgYWtPD/tzPKqWybmMCkM/DEnS3QcNFo3UrDGnKS6ZeM/wBOg=
  - git submodule update --init --recursive
after_success: bash deploy.sh
